# define all locations, HRRR Variables, and time range, then fetch data

## imports

In [ ]:
import logging
from pathlib import Path
from datetime import datetime

from pyhrrrzarr.schema import csv_to_locations
from pyhrrrzarr.hrrr.schema import HRRRVariable, VariableName, Level 
from pyhrrrzarr.hrrrzarr.requests import create_requests
from pyhrrrzarr.hrrrzarr.fetch import get_all_request_values
from pyhrrrzarr.hrrrzarr.postprocess import requests_to_df, add_wind_speed_and_direction


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

## create all requests for data

In [ ]:
import pandas as pd


csv_path = Path("../data/IBM_locations.csv").resolve()
df = pd.read_csv(csv_path)
if df.shape[0] == len(df.station_id.unique()):
    logger.info("station_id is unique")
else:
    logger.error("station_id is not unique")

df.head()

INFO:__main__:station_id is unique

,network,station_id,station_name,station_lat,station_lng,ibm_lat,ibm_lng
0,NDAWN,CRRN,Carrington,47.508650,-99.132150,47.494505,-99.140639
1,NDAWN,CSSL,Casselton,46.879950,-97.223020,46.879121,-97.207045
2,NDAWN,CRKS,Crookston,47.823333,-96.620556,47.802198,-96.635756
3,NDAWN,DCKN,Dickinson,46.894830,-102.812840,46.879121,-102.832044
4,NDAWN,GLYN,Glyndon,46.866280,-96.567630,46.879121,-96.547866

In [ ]:
# csv_path = Path("../data/WiscoNet pre-2024 stations.csv").resolve()
keys: dict[str, str] = {
    "lat": "ibm_lat",
    "lon": "ibm_lng",
    "name": "station_id",
}
locations = csv_to_locations(csv_path, keys=keys)
logger.info(f"total number of locations: {len(locations)}")
locations[:5]

total number of locations: 36

[Location(lat=47.49450549450549, lon=-99.140638857275, name='CRRN'),
 Location(lat=46.87912087912088, lon=-97.20704543864464, name='CSSL'),
 Location(lat=47.80219780219779, lon=-96.63575647404927, name='CRKS'),
 Location(lat=46.87912087912088, lon=-102.83204447466028, name='DCKN'),
 Location(lat=46.87912087912088, lon=-96.54786586411154, name='GLYN')]

In [22]:
vars = [
    HRRRVariable(name=VariableName.TMP, level=Level._2M_ABOVE_GROUND),
    HRRRVariable(name=VariableName.DPT, level=Level._2M_ABOVE_GROUND),
    HRRRVariable(name=VariableName.APCP_1hr_acc_fcst, level=Level._SURFACE, type_model="fcst"),
    HRRRVariable(name=VariableName.RH, level=Level._2M_ABOVE_GROUND),
    HRRRVariable(name=VariableName.UGRD, level=Level._10M_ABOVE_GROUND),
    HRRRVariable(name=VariableName.VGRD, level=Level._10M_ABOVE_GROUND),
]
start=datetime(2024, 1, 1, 0, 0)
# end=datetime(2024, 9, 2, 0, 0)
end=datetime.now()
requests = create_requests(
    locations=locations,
    variables=vars,
    start=start,
    end=end
)

INFO:root:Created 1669248 requests

# pull data from s3 and/or local cache

In [23]:
# around 4 hours for 620928 requests from s3, same number of requests in around 20 minutes from local cache
requests = await get_all_request_values(requests, batch_size=5500)

Fetching HRRR data:   0%|          | 0/1669248 [00:00<?, ?it/s]

decompressing:   0%|          | 0/1669248 [00:00<?, ?it/s]

# post process data to dataframe, calculate wind speed and direction

In [24]:
df = requests_to_df([r for r in requests if r.value is not None])
df = add_wind_speed_and_direction(df)
df.tail()

INFO:pyhrrrzarr.hrrrzarr.postprocess:Converted 1669248 requests to DataFrame rows
INFO:pyhrrrzarr.hrrrzarr.postprocess:Added 278208 wind speed and 278208 wind direction rows

,location,lat,lon,run_hour,var_name,var_level,value,units
2225659,OJNR,43.010989,-89.560562,2024-11-17 23:00:00,WIND_DIR,10m_above_ground,243.126056,degrees
2225660,SODO,44.769231,-87.363297,2024-11-17 23:00:00,WIND_DIR,10m_above_ground,254.376853,degrees
2225661,RNLD,45.648352,-89.252945,2024-11-17 23:00:00,WIND_DIR,10m_above_ground,247.539599,degrees
2225662,SPNR,45.824176,-91.845718,2024-11-17 23:00:00,WIND_DIR,10m_above_ground,206.990326,degrees
2225663,WCRS,44.197802,-90.747086,2024-11-17 23:00:00,WIND_DIR,10m_above_ground,234.361496,degrees

# persist postprocessed data to disk

In [25]:
csv_path = Path("../data/Wisconet_and_NDAWN_stations_2024_IBM_lat_lon_HRRR_data.csv").resolve()
parquet_path = csv_path.with_suffix(".parquet")
df.to_parquet(parquet_path)
df.to_csv(csv_path)